### ISSUE TITLE
settings cut off

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#328]
The settings are cut off. This is noticeable in portrait format, but especially in landscape format.

Android13
20-20241011-dos-taimen

![Screenshot_20241013-131357_Raccoon](https://github.com/user-attachments/assets/33663be7-c79f-42ba-9c2a-7bdb95cbaf14)
![Screenshot_20241013-131424_Raccoon](https://github.com/user-attachments/assets/57481f2f-4bb0-437c-9d40-6d9459bf6e30)

**Comment by AkesiSeli** [comment]
Sorry, I am terribly sorry for that 😱 I simply forgot to add a `verticalScroll` modifier on the vertical list and I feel terribly dumb for that.
