### ISSUE TITLE
[Packaging] Create a repo for F-Droid

### ISSUE THREAD

**Issue by Cicorione** [LiveFastEatTrashRaccoon/RaccoonForFriendica#375]
Hi, I'd like to test your Android app, could you submit your app to F-Droid or create a repo for it?

Thanks in advance! 🙏

**Comment by AkesiSeli** [comment]
Yes, I never managed to have any app published by them (not even the Lemmy client) but I can try. They will not like Sentry as a crash reporting system but maybe if I declare it as an anti-feature it can do...

**Comment by Cicorione** [comment]
Hope you can achieve it! 🙏

**Comment by AkesiSeli** [comment]
On second thoughts, I'd better keep Sentry as reporting system while the app is in beta. Once I manage to get a stable release, I'll remove Sentry entirely and try the submission to F-Droid.

**Comment by darhma** [comment]
Using sentry as a crash reporting system should not be a big problem for publishing the app in the official f-droid repo: if it is used as an opt-in I don't think it is even reported as anti-feature, otherwise anti-feature tracking is reported (https://f-droid.org/docs/Anti-Features/#Tracking)

**Comment by AkesiSeli** [comment]
I've made it opt-in in #494 after discussing about how to avoid anti-features for the inclusion on IzzyOnDroid. Since now I have a "stable" version, I can actually start the submission... it will be fun (and surely a lot of trial and error will be needed to make their pipeline succeed)

**Comment by AkesiSeli** [comment]
Here is the link to the [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16636) on F-Droid Metadata repo.

Just he fact that the pipeline is passing 🟢 and that the build is reproducible is some really good news!

**Comment by AkesiSeli** [comment]
Closing this one because the MR has been merged 🎉
