### ISSUE TITLE
Standard timelines: allow the selection of channels

### ISSUE THREAD

**Issue by loma-one** [LiveFastEatTrashRaccoon/RaccoonForFriendica#380]
With the channels Friendica offers the possibility to create your own timeline. These timelines are equal to the existing timelines. Allow a self-made timeline to be selected as the standard timeline

### steps

1. sandwitch > Settings
2. menu item ‘Standard timelines’
3. select the timeline
4. make sure that further posts are retrieved when the last post is reached.

### Actual Result:

Currently only the timelines ‘all; subscriptions; local’ can be selected

### Expected Result:

The timeline ‘all; subscriptions; local’ and channels can be selected

Note: the channels are currently labelled as ‘circles’. This is probably because the Friendica project may declare the channels incorrectly so that channels are displayed via Mastodon-compatible apps.

**Comment by AkesiSeli** [comment]
I see the issue: they can now be selected only in the Home screen if you tap on the top app bar (where it says "All/Local/Subscriptions" next to the sandwich) but it makes sense to be able to select the default one in the Settings screen.

p.s. Your guess is correct, Circles and Channels are returned in the same list as if they were Mastodon user-defined lists for compatibility.
