### ISSUE TITLE
Riavvio improvviso 

### ISSUE THREAD

**Issue by H9kk** [LiveFastEatTrashRaccoon/RaccoonForFriendica#436]
Ogni volta che faccio una ricerca user o hashtag l'app si chiude e si riavvia non succede facendo una ricerca di una parola chiave in un post .

**Comment by AkesiSeli** [comment]
Grazie, trovato e risolto! Errore, ovviamente, stupido e dovuto alla fretta: nel tentativo di aggiungermi nei report un'informazione relativa a un problema esistente ne ho aggiunto un altro

![I'm stupid meme](https://media.makeameme.org/created/im-stupid-80281ad2f1.jpg)
