### ISSUE TITLE
minor spelling error in fastlane full_description.txt breaks formatting

### ISSUE THREAD

**Issue by IzzySoft** [LiveFastEatTrashRaccoon/RaccoonForFriendica#486]
[this line](https://github.com/LiveFastEatTrashRaccoon/RaccoonForFriendica/blob/master/fastlane/metadata/android/en-US/full_description.txt#L36) should be `</ul>`, not `<ul>` :wink:

(same in `it-IT`)

**Comment by IzzySoft** [comment]
That was fast, thanks! And congrats: the Raccoon is reproducible! And now also [available at IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.livefast.eattrash.raccoonforfriendica) – be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme :smiley:

What I couldn't figure out: is Sentry enabled by default, or is it opt-in?

**Comment by AkesiSeli** [comment]
Sentry is enabled by default because I was planning to remove it once it exits the beta phase... do you think that if I make it opt-out by default with optional opt-in it may make it easier to get approval on FOSS stores?

**Comment by IzzySoft** [comment]
@AkesiSeli is there an ETA for a tag marked "release" (and not "pre-release")? I just notice the builder yells as it cannot find https://api.github.com/repos/LiveFastEatTrashRaccoon/RaccoonForFriendica/releases/latest (which is not available if there are only pre-releases). If it takes longer, I must see to change the settings for the Raccoon to go via tags instead, which is a little more complicated – or keep track of updates manually, or it won't update the RB status for new releases.

**Comment by AkesiSeli** [comment]
Sorry for the inconvenience! I've already made crash reports opt-out [here](https://github.com/LiveFastEatTrashRaccoon/RaccoonForFriendica/pull/494) and I am waiting some more days more until @informapirata and me complete the tests.

It should be by the end of this week and the beginning of the next one. Btw, would it be possible to change the category of the app as "Clients for Mastodon & Pleroma" rather than "Various federated networks"? Friendica falls in the second groups but Raccoon is fully compatible with Mastodon too (actually there are features like polls which work better on Mastodon than on Friendica).

**Comment by IzzySoft** [comment]
> I've already made crash reports opt-out

Thanks! For dropping the anti-feature they'd need to be opt-in, though.

> It should be by the end of this week and the beginning of the next one.

Great, thanks! For less than a week I can "ignore" the errors thrown here by the update-checker.

> Btw, would it be possible to change the category of the app as "Clients for Mastodon & Pleroma" rather than "Various federated networks"? Friendica falls in the second group but Raccoon is fully compatible with Mastodon too

Oh! Why, then we should put it in both places I'd say (done). Maybe the app description should make that clearer, too? I had to Ctrl-F to find the only mention of Mastodon in the description. Currently, the first paragraph reads:

> Raccoon for Friendica is a free and open source mobile-first Friendica client.

Maybe that should better read

> Raccoon for Friendica is a free and open source mobile-first client for Friendica and Mastodon.

?

**Comment by AkesiSeli** [comment]
Sorry my English s*cks... I meant "crash reports are now disabled by default and users must turn on a switch in the settings screen and restart the app to enable them".

**Comment by IzzySoft** [comment]
OK, that describes opt-in :smile: Please give me a ping when that part made it into a release, so I can remove the anti-feature and add Sentry to the app's "green list" then.

**Comment by AkesiSeli** [comment]
It will enter the next version, which will also be the first non "pre-release" one, I'll give you a ping when it's released.

**Comment by AkesiSeli** [comment]
@IzzySoft the [latest release](https://github.com/LiveFastEatTrashRaccoon/RaccoonForFriendica/releases/tag/0.1.0) is now available, so the job should not complain any more!

**Comment by IzzySoft** [comment]
Oops, forgot to confirm – done hereby, thanks!

**Comment by AkesiSeli** [comment]
Thanks for the confirmation, I had seen it... in the meantime I'm trying to get an approval even on F-Droid.

**Comment by IzzySoft** [comment]
I don't remember having to have to change anything here, and this one "simply happened":

![image](https://github.com/user-attachments/assets/f9491157-62b7-4881-b02e-d2ce741e6885)

the first shield says it's RB, so the auto-update worked :smiley:
