### ISSUE TITLE
[Inbox] Notification filter is not applied

### ISSUE THREAD

**Issue by AkesiSeli** [LiveFastEatTrashRaccoon/RaccoonForFriendica#530]
When filtering notifications and excluding certain categories, all results are still displayed.

Expected result: only notifications of the selected categories should appear in the list after filtering.

**Comment by toas-koas** [comment]
The error persists, if I remove a checkmark and restart the app, all checkmarks are set again.

Android 14
Version 0.3.2-beta06
com.livefast.eattrash.raccoonforfriendica

**Comment by AkesiSeli** [comment]
Note: there is a Friendica bug due to which notifications are not filtered, as noted in the PR description:
https://github.com/friendica/friendica/issues/14427

Do you want filters to persist across app closing/opening? I'll have to implement because they were not intended to be persistent.

**Comment by toas-koas** [comment]
Yes, I would like the filter to remain in place. I've set it up the same way on the web and the filter remains in place. It would be good if this were also the case in the app.
