### ISSUE TITLE
[UI] MaterialYou setting gets disabled

### ISSUE THREAD

**Issue by licaon-kter** [LiveFastEatTrashRaccoon/RaccoonForFriendica#550]
...when changing instance

...when restarting the app

0.2.1, Android 14

**Comment by AkesiSeli** [comment]
I assume this is happening only for anonymous (not logged in) users. I'll look into it!

**Comment by AkesiSeli** [comment]
I've found and fixed the issue, it was a really trvial bug which I oversaw (even in unit tests). 🙈
