### ISSUE TITLE
Overlaying images

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#607]
**Describe the bug**
If two consecutive posts contain images, these posts are often overlapped with images. It doesn't matter whether they are posts with images only or whether the post contains an image from the link preview.

**Smartphone (please complete the following information):**
 - Device: Pixel2XL
 - OS: Android 14

![Screenshot_20241130-230746_Raccoon.png](https://github.com/user-attachments/assets/8f5f88c3-36e9-417a-99c6-ab17ccebcf1b)

![Screenshot_20241202-103326_Raccoon.png](https://github.com/user-attachments/assets/f3cc8ef4-0daf-48b5-ba76-1cbf046acfde)

**Comment by AkesiSeli** [comment]
Looks to me the app is not handling correctly image bounds, maybe sometimes the original size is not returned from the backend (this regularly happened for GIFs as far as I recall). I'll have a look at it.

**Comment by toas-koas** [comment]
Das Problem besteht  in der Version weiterhin
Version 0.3.2-beta06
com.livefast.eattrash.raccoonforfriendica

**Comment by toas-koas** [comment]
Screenshot
![Screenshot_20241212-170122_Raccoon](https://github.com/user-attachments/assets/f3452149-50ae-48d2-af20-b2eb993de645)

**Comment by AkesiSeli** [comment]
Thanks, unfortunately I can not reproduce, even registering on anonsys.net and exploring the timeline...

**Comment by toas-koas** [comment]
Go to this profile and scroll down
https://fedi.fabrykajabo.li/users/9ypxwaiwo18rzcjo

![Screenshot_20241214-103955_Raccoon](https://github.com/user-attachments/assets/2b31e835-d397-476e-a7bd-7690dd1d383b)

**Comment by AkesiSeli** [comment]
@toas-koas did version [0.3.2-beta07](https://github.com/LiveFastEatTrashRaccoon/RaccoonForFriendica/releases/tag/0.3.2-beta07) improve anything on this side? The latest beta has included #637 which may have solved (or at least mitigated) the issue, which I could not reproduce unfortunately.

**Comment by toas-koas** [comment]
The error is still there
See e.g. this post
https://mastodon.com.br/@elmoneto/113674326392310169

**Comment by AkesiSeli** [comment]
That is actually some good news because finally I managed to reproduce it and solved it!
