### ISSUE TITLE
[Post creation] No thumbnail preview of images

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#608]
**Describe the bug**
When I write a post and add pictures, they are not displayed as thumbnails at the bottom of the post.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 14

![Screenshot_20241125-144059_Raccoon.png](https://github.com/user-attachments/assets/aeed2f67-26b6-4f21-91ea-bf047c5ca3ea)

**Comment by AkesiSeli** [comment]
They should definitely appear... are you using the app with Friendica or Mastodon? And, if I can ask, what is your instance? I need this information only to determine whether it happens only with certain backend-types and/or version of back-end software.

**Comment by toas-koas** [comment]
I use it with Friendica
My instance is anonsys.net

**Comment by AkesiSeli** [comment]
I confirm I can reproduce on that instance (not in my usual one).

I'll investigate, maybe it depends on the Friendica version since I see they are running `2024.09-rc` which I haven't tested Raccoon against.

**Comment by AkesiSeli** [comment]
Found the bug! The app fails to detect it as a Friendica server and thinks it is on Mastodon. This is why you don't have access to the calendar, gallery, direct messages, BBCode editing and the upload of images is done "the Mastodon way".

 Sorry for the inconvenience and for making you wait until now, I'll fix it asap and release a new version of the app.
