### ISSUE TITLE
[Timeline] Disable preview card and attachments - create post layouts

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#633]
I would like it if you could deactivate the link preview in the settings.

**Comment by AkesiSeli** [comment]
Please correct me if I understand the request correctly: you would like to have a setting option to ignore the post "preview card" in timelines? I. e. seeing just the author, title (if present), spoiler (if present), post body and attachments but **not** the preview (the part which appears in the rounded square)?

<div align="center">
<img src="https://github.com/user-attachments/assets/881a7981-7e07-4f56-98c6-259cb1756fd5" />
</div>

**Comment by toas-koas** [comment]
I would like only the text of the post to be displayed without any preview. This can be set in the web interface so that only the text is displayed in the feed.

**Comment by AkesiSeli** [comment]
Ok so neither preview nor attachments I guess. I'll have a closer look at the web interface to get a better idea. It can be done fairly easily... but I'll not just add a yes/no option in settings, I'll make it possible to choose different post layouts.

I think it gives users more flexibility. I'll make the "compact" mode look as you ask then I'll think of another 1-2 possible layouts.

This is quite common in other "regions" of the Fediverse, like Lemmy... so I'll reuse the considerations done for the other app. I don't know why most Mastodon clients tend to prefer "fix" layouts.
