### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by toas-koas** [LiveFastEatTrashRaccoon/RaccoonForFriendica#647]
When I open the app, it crashes when loading the timeline.
I have closed the app and also restarted the phone. The error remains.

Version 0.3.2-beta06
com.livefast.eattrash.raccoonforfriendica
LineageOS 21
Pixel 2XL

**Comment by AkesiSeli** [comment]
I've seen the bug, it is due to some HTML in a post which crashes the parser.
