### ISSUE TITLE
Handle and allow playing audio files attached to posts

### ISSUE THREAD

**Issue by pvagner** [LiveFastEatTrashRaccoon/RaccoonForFriendica#659]
It would be nice to also handle audio files attached to posts the same way or similar how videos are handled now.
When encountering a post with audio attachment it should be possible to open it in the same player we can now open video files.
Also there is already request for attaching arbitrary files to new posts (#538) when composing. This should of course include audio files such as .mp3, .m4a, .opus and .ogg even .flac and .wav if there is nothing else blocking these file types from being available.
Example post with audio file attachment: https://convo.casa/@Blindy/113677352592467123
The same thing from friendica: https://fedi.ml/display/572bad98-affcfc04bb5b7493-dc1228dc

Thanks for considering and researching it.

**Comment by AkesiSeli** [comment]
Yes, correct... the issue you mention is about adding attachments of different types (including audio files). I would keep this one as a reminder for me to support audio playback in posts just as we already do with videos.

Thanks for the idea, I would consider it for the next "minor" release (0.4.0) and I think it would add a quality-of-life improvement to end users.
