### ISSUE TITLE
App crash 0.3.3

### ISSUE THREAD

**Issue by marcdw1289** [LiveFastEatTrashRaccoon/RaccoonForFriendica#664]
**Describe the bug**
Upon launch it seems the timeline is trying to be loaded, the app crashes.

**To Reproduce**
1. Launch Raccoon
2. Raccoon closes after failing to load timeline

**Expected behavior**
Raccoon should display timeline at startup.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: crDroid 7.18 (Android 11)
 - Version 0.3.3

**Additional context**
May be similar to #647 (?).

[crash-com-livefast-eattrash-raccoonforfriendica-19_12-21-49-02_973.zip](https://github.com/user-attachments/files/18206634/crash-com-livefast-eattrash-raccoonforfriendica-19_12-21-49-02_973.zip)

**Comment by AkesiSeli** [comment]
Yes, it's always related to HTML rendering like the other one, but the error is slightly different (probably due to some weird element nesting). I'll have a look at it even if at the moment having the app build be reproducible again is a priority.
