### ISSUE TITLE
[l10n] Incorrect format specifier in hashtag list subtitle

### ISSUE THREAD

**Issue by PulpyPulpy** [LiveFastEatTrashRaccoon/RaccoonForFriendica#704]
**Describe the bug**
%d instead of numbers

**To Reproduce**
1. Go to in hashtag
2. See error

Hello, not sure it is a raccoon or friendica bug, I am trying to help. 
See screenshot 
![Screenshot_20241231_104209_com_livefast_eattrash_raccoonforfriendica_MainActivity](https://github.com/user-attachments/assets/8061ef70-56ab-45c7-a11d-30fdecd9cc0d)

**Comment by AkesiSeli** [comment]
It's a bug due to… me! I mistyped the placeholder using `$1%d` instead of `%1$d` in a couple of plural strings in the English source, then the error was propagated across various languages during translation.

I'll fix it asap, thanks for reporting it!
